### ISSUE TITLE
NullPointer exception in `onActivityResult` on Android

### ISSUE THREAD

**Issue by vandres** [Hina-Hussain/open_apps_settings#1]
I am using the image_picker package for selecting an image through the user. After the user has chosen an image, the native dialog is closing and I am getting a NullPointer from your plugin. It seems, if another plugin is triggering a native dialog, the property `activityRes` is null.

I hotfixed it for us like this:

```
  @Override
  public boolean onActivityResult(int requestCode, int resultCode, Intent data) {
    if (activityRes != null) {
      activityRes.success(""+requestCode);
    }
    return true;
  }
```

**Comment by Hina-Hussain** [comment]
@vandres Thank you for pointing out the issue. The issue has been resolved in the 0.0.4 version released.
